### ISSUE TITLE
Feature request: cone element

### ISSUE THREAD

**Issue by ckohnke** [Eternita-S/Splatoon#14]
Having a cone element where the user can define a radius and an angle, and has lines connected to the reference location to mark boss AOEs (i.e. Boss A does a 270 degree cleave, Boss B does a 350 degree cleave, where is it safe? I don't want to aggro this mob in Zadnor/Eureka/Deep Dungeon, where can it see?) and can account for rotation would be nice.

Currently this can be achieved clunkily with circle + multiple line elements, but it doesn't look very good.

**Comment by Eternita-S** [comment]
Hello!
This can be done and definitely something I'm looking forward to add. However cones aren't easy to implement properly, so that is only going to be happening in post 6.0 updates.

**Comment by kaedys** [comment]
Also, when configuring a cone, it'd be nice to be able to set the "far side" of the cone, relative to the anchor point, to either be a flat line (ie. a triangle, as if the cone were cut out of a rectangle) or a circular arc (as if the cone were a pizza slice of a circle).    Also, for the purposes of drawing a "border" element for said cone (ie. separate elements that show the edges of the cone area more brightly), it would be useful if we could limit a circular draw element to only a certain portion of the circle (ex. only draw 90 degrees of the circle), with the definition being either the degrees of arc to draw and the offset, or the degrees of arc and the angle of the "center" of the arc.  Either would allow the placement of arbitrarily-angled and sized partial circles around a target or point of orientation.

**Comment by kaedys** [comment]
Saw the latest release implemented filled circles.  If we could get a cone restriction on the circle (ie. only render X degrees of the circle, along with the angle offset that lines relative to a target have, that along with the new filled-circle feature (presuming the two work together), would perfectly fill my use-case above.

**Comment by Eternita-S** [comment]
Unfortunately there is a bug in the game function that splatoon relies on which creates big obstacles when it comes to custom shapes, including cones and rectangles. This is also why polygons are not and thing yet and why lines with radius will be distorted when they are crossing corner of the screen. 

Using world to screen function on points behind the screen results in such points being calculated to invalid coordinates. Like this:
https://imgur.com/a/4pkgiYL
This is what happens if point of a line is behind the screen. For recording this example I've disabled workaround that fixes this issue, you shouldn't be able to recreate it.
However when it comes to shapes more complex than line I don't know how to transform them to be within visible boundaries. This is what majorly prevents further development of the plugin - even if it is possible to do transformation like this, I don't yet know how.
Example of transformations that needs to be done:
![image](https://user-images.githubusercontent.com/5073202/158990539-a976d824-da65-4b07-bd91-6bc62fd5f51a.png)
On a positive note going just a bit behind the screen does not results in any problems, only relatively far distances will cause problems.

Additional problem is that the transformation must be done with game coordinates, before they have been converted to screen coordinates. So basically we need to transform in-game coordinates that way so when they are converted to screen coordinates  they would result correctly cut shape.

Again, at this point of time I don't know how to approach this problem. It would be really good if someone could help me with algorithm.

**Comment by kaedys** [comment]
My gut reaction, without having analyzed it much, would be to see if you could convert screen coordinates to in-game coordinates.  That would let you delineate where the edges of the "view" are, as they are projected on the game world, and therefore the x/y/z limits of the projected shapes.  I don't know how feasible this is within the context of the game client or the mod, however.  I would _think_ there's some mechanism to do it, though, because that same mechanism would be needed to, for example, figure out which bit of terrain the mouse is currently hovering over for ground-target effects.  

Assuming that's possible, a plane can be defined for each edge of the screen, which extends from the camera position to the terrain (or skybox), defined by the camera position and any two points on that terrain or skybox (you need 3 points to define a plane).  For simplicities sake, it probably easiest to project each of the _corners_ of the screen onto the terrain, as that lets you re-use each of those points (since each corner is a point on two planes, for each of the two screen sides it connects).  The normal vector of a plane can be found simply by the cross-product of any two vectors in the plane (hence the need for 3 points).  

If we define position P₀ as the camera position (in world coordinates), and the positions P₁ and P₂ as the world coordinates of two adjacent corners of the screen (say, the bottom left and bottom right), as they are projected on the game world (or anywhere in that line, tbh), then our two vectors become:

```
P₀P₁ = (X₀ - X₁, Y₀ - Y₁, Z₀ - Z₁)
P₀P₂ = (X₀ - X₂, Y₀ - Y₂, Z₀ - Z₂)
```

The cross-product of any two vectors, simplified, is:

```
X = Y₁Z₂ - Z₁Y₂
Y = Z₁X₂ - X₁Z₂
Z = X₁Y₂ - Y₁X₂
```

Substituting the differences above for our vectors, then our plane normal becomes (where the subscripts 0, 1, and 2, respectively, once again refer to the Camera, screen corner 1, and screen corner 2, in world coordinates):

```
X = (Y₀ - Y₁)(Z₀ - Z₂) - (Z₀ - Z₁)(Y₀ - Y₂)
Y = (Z₀ - Z₁)(X₀ - X₂) - (X₀ - X₁)(Z₀ - Z₂)
Z = (X₀ - X₁)(Y₀ - Y₂) - (Y₀ - Y₁)(X₀ - X₂)
```

We define this as the plane normal `n`.  With the plane normal, we can then define the intersection point of any line or vector with that plane (pulled from https://en.wikipedia.org/wiki/Line%E2%80%93plane_intersection).  If a line is drawn from point L₁ to L₂, we get line L:

```
L = (L₁X - L₂X, L₁Y - L₂Y, L₁Y - L₂Y)
```

The equation for that line is then:

```
p = L₀ + L*d
```
Where L₀ is an arbitrary point in the line (L₁ and L₂ being the obvious options), and `d` is an arbitrary scalar.

Substituting into the plane equation and solving for the scalar, we get:

```
d = ((P₀ - L₀)·n) / (L·n)
```
Where `·` here is the dot product.  In the special case where `L·n` is 0, the vector and plane are parallel.  Then we can use the above equation for the line, substituting either endpoint of the line for L₀ and the above computed `d` for the scalar, to find the point where the vector intersects the plane.

Thus for any line in which one of the two points is not on the screen and the other is, we can compute the point where that line intersects the visual edge of the screen (the plane above) and instead draw the line to that point instead.

I'd have to play with the equations for a bit for more complex shapes like cones, but I hope that gives you a starting point.  And of course, this is all entirely moot if there's no convenient way to transform the coordinates of the corners of the screen, as they project onto the terrain, into world coordinates.

**Comment by Eternita-S** [comment]
Thanks for the thoughts!
There is a function that converts screen coordinates to world but it only can do it if there is surface area, and it will place height onto surface area too. 
![image](https://user-images.githubusercontent.com/5073202/159126910-15849c20-e81f-4890-a392-7aa0bb948b39.png)
hmm, but if it was possible to force game to think that there always is surface at certain height... I need to look at screen to world function, maybe that'll give me some idea.

**Comment by kaedys** [comment]
Hmm, that does put a bit of a hamper on it.

Hmm...well, the vector for all 4 corners are the same, just reflected around the center of the screen (specifically, the vertical and horizontal axis, which in theory would require another point to resolve, but you could probably infer it from screen resolution.  Probably.), so if you have a vector to the center and a vector to a corner, you have a vector to all 4 corners.  And if _none_ of the 4 corners are resolving, that begs the question whether we need to be worrying about points that are behind the camera.

Oh, another option I just thought of.  So, assuming you can get the world coordinates of the camera, and the world coordinates of the center of the screen (or, potentially, infer where the screen center is from the world coordinates of anywhere else on the screen that _does_ resolve, and then use the screen offset of that position combined with the display aspect ratio and field of view settings to find where the center of the screen would be), you could treat the _camera view_ (ie. camera position to where the camera center resolves to) as the normal vector of the collision plane and the camera position as the point in the plane (shifted a smidge forward, though, so the plane exists "in front of" the camera), and then use _that_ as the plane to collide lines with and use the above transformation on.  That would save needing to find the screen corners at all, all you would need is the world positions of the camera and the screen center.  Though that's assuming that my inference from the above animation is correct, where the issue occurs once the point goes "behind" the camera, rather than simply when it is off screen.

**Comment by Eternita-S** [comment]
Cone element has been added in 1.0.9.0 update, however with certain limitations.
