### ISSUE TITLE
Feeature Request: Add option for triggers to fire specific elements

### ISSUE THREAD

**Issue by SashaFFXIV** [Eternita-S/Splatoon#48]
Would allow #47 to be contained within a single layout.

**Comment by Eternita-S** [comment]
Hello! Instead of adding options for specific elements I have plans to allow layouts to be grouped up into groups. It will be done as a part of big gui update, once ultimate/savage prog calms down (I do not want to implement major changes to the plugin for now while a lot of people progressing through the fight)

**Comment by SashaFFXIV** [comment]
Sounds neat! Thanks for the quick responses.
